blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('my_blog.urls')),
]

my_blog/urls.py
#Define URL patterns for my_blog

from django.urls import path

from . import views

app_name = 'my_blog'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),

    #Page that shows all topics
    path('topics/', views.topics, name='topics'),

    #Detail page for a topic
    path('topics/<int:topic_id>', views.topic, name='topic'),

    # Page for adding a topic
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page for adding new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    

]

users/urls.py
from django.urls import path, include

app_name = 'users'
url_patterns = [
    path('', include('django.contrib.auth.urls')),
]

my_blog/models.py
from django.db import models

class Topic(models.Model):
    "a topic to write about"
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text[:50]

users/models.py
from django.db import models

# Create your models here.

my_blog/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

my_blog/views.py
from django.shortcuts import render, redirect

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    #Home page for my_blog
    return render(request, 'my_blog/index.html')

def topics(request):
    #Show all topics
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'my_blog/topics.html', context)

def topic(request, topic_id):
    #Detail page for a topic
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'my_blog/topic.html', context)

def new_topic(request):
    #Add new topic
    if request.method != 'POST':
        #No data submitted, create a blank form.
        form = TopicForm()
    else:
        #POST data submitted
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('my_blog:topics')
    
    #Display a blank form
    context = {'form': form}
    return render(request, 'my_blog/new_topic.html', context)

def new_entry(request, topic_id):
    #Add new entry for a topic
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted
        form = EntryForm()
    else:
        # POST data submitted
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('my_blog:topic', topic_id=topic_id)
        
    #Display blank form
    context = {'topic' : topic, 'form': form}
    return render(request, 'my_blog/new_entry.html', context)

def edit_entry(request, entry_id):
    #Edit an existing entry
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        #Initial request, pre-fill with current entry.
        form = EntryForm(instance=entry)
    else:
        #Post data submitted
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('my_blog:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'my_blog/edit_entry.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

my_blog/templates/my_blog/base.html
<p>
    <a href={% url 'my_blog:index' %}>My Blog</a>
    <a href={% url 'my_blog:topics' %}>Topics</a>
</p>

{% block content %}{% endblock content %}

my_blog/templates/my_blog/edit_entry.html
{% extends "my_blog/base.html" %}

{% block content %}

    <p><a href="{% url 'my_blog:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>

    <form action="{% url 'my_blog:edit_entry' entry.id %}" method='POST' >
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Save changes</button>
    </form>

{% endblock content %}

my_blog/templates/my_blog/index.html
{% extends "my_blog/base.html" %}

{% block content %}
<p>My blog will help keep track of my learning, for any topic I'm learning about.</p>
{% endblock content %}

my_blog/templates/my_blog/new_entry.html
{% extends "my_blog/base.html" %}

{% block content %}

    <p><a href="{% url 'my_blog:topic' topic.id %}" method='POST' >{{ topic }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'my_blog:new_entry' topic.id %}" method='POST' >
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Add entry</button>
    </form>

{% endblock content %}

my_blog/templates/my_blog/new_topic.html
{% extends "my_blog/base.html" %}

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'my_blog:new_topic' %}" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>


{% endblock content %}

my_blog/templates/my_blog/topic.html
{% extends "my_blog/base.html" %}

{% block content %}

<p> {{topic}} </p>

<p>Entries:</p>
<p>
    <a href="{% url 'my_blog:new_entry' topic.id %}">Add a new entry</a>
</p>


<ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <a href="{% url 'my_blog:edit_entry' entry.id %}">Edit entry</a>
            </p>
        </li>
    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>



{% endblock content %}

my_blog/templates/my_blog/topics.html
{% extends "my_blog/base.html" %}

{% block content %}

    <p>Topics</p>

    <ul>
        {% for topic in topics %}
            <li>
                <a href="{% url 'my_blog:topic' topic.id %}">{{ topic }}</a>
            </li>
        <!--If topcs is empty-->    
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'my_blog:new_topic' %}">Add a new topic</a>

{% endblock content %}